version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::824340209398:user/Administrator"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::824340209398:user/Administrator"
cloudformation_execution_role = "arn:aws:iam::824340209398:user/Administrator"
artifacts_bucket = "user/Administrator"
image_repository = ""
region = "ap-southeast-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::824340209398:user/Administrator"
cloudformation_execution_role = "arn:aws:iam::824340209398:user/Administrator"
artifacts_bucket = "user/Administrator"
image_repository = ""
region = "ap-southeast-1"
